### ISSUE TITLE
Little update needed

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoDocs#8]
1. http://shokoanime.com/version-3-6-brings-speed-and-streaming/ is pointing to old domain + there is nothing under /streaming at new domain (did some data got lost? is there anything to read ?)
2. http://shokoanime.com/downloads/ - could you update nakamori plugin status and links to source (from ancient link to newest ?- we did change name on github )

**Comment by ElementalCrisis** [comment]
Sure, I'm out of town until Friday so I'll do it when I get back.

**Comment by ElementalCrisis** [comment]
Done.

**Comment by bigretromike** [comment]
you forgot `:` in that `Checkout our streaming documentation which should ` link

**Comment by ElementalCrisis** [comment]
It doesn't matter, the link just points to the site and its a 9 month old post at this point.

**Comment by bigretromike** [comment]
i was hoping to see that 'streaming' doc ;p and was thinking you missed it, but as its not there the ok.

**Comment by ElementalCrisis** [comment]
We used to have a separate page for streaming info but since @maxpiva made it automatic, it made that page redundant. So I added a [question on the FAQ ](http://docs.shokoanime.com/faq.html#collection-stream)that pretty much covers what you need to know.

**Comment by bigretromike** [comment]
not really but will check it latter in code as there is a lot unknown for me with that one.
also, any eta for release ?
